(function() {var implementors = {};
implementors["dist_tracing"] = [{"text":"impl&lt;S, V:&nbsp;<a class=\"trait\" href=\"tracing_core/field/trait.Visit.html\" title=\"trait tracing_core::field::Visit\">Visit</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static, T:&nbsp;'static + <a class=\"trait\" href=\"dist_tracing/trait.Telemetry.html\" title=\"trait dist_tracing::Telemetry\">Telemetry</a>&lt;Visitor = V&gt;&gt; <a class=\"trait\" href=\"tracing_subscriber/layer/trait.Layer.html\" title=\"trait tracing_subscriber::layer::Layer\">Layer</a>&lt;S&gt; for <a class=\"struct\" href=\"dist_tracing/struct.TelemetryLayer.html\" title=\"struct dist_tracing::TelemetryLayer\">TelemetryLayer</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;S: <a class=\"trait\" href=\"tracing_core/subscriber/trait.Subscriber.html\" title=\"trait tracing_core::subscriber::Subscriber\">Subscriber</a> + for&lt;'a&gt; <a class=\"trait\" href=\"tracing_subscriber/registry/trait.LookupSpan.html\" title=\"trait tracing_subscriber::registry::LookupSpan\">LookupSpan</a>&lt;'a&gt;,&nbsp;</span>","synthetic":false,"types":["dist_tracing::telemetry_layer::TelemetryLayer"]}];
implementors["tracing_subscriber"] = [];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()